ServicesUrl:
    PolicyApiUrl: http://Microservices.Demo.Policy.API/api/policiesVersion 
    ProductApiUrl: http://Microservices.Demo.Product.API/api/products  
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Policy.API
    Environment: production
